using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ehr.Common.Constraint
{
    public enum Antimicrobial
    {
        NONE = 0,
        AMIKAXIN = 1,
        AMOXICILIN = 2,
        AMPICILLIN = 3,
        APRAMYCIN = 4,
        BACITRACIN = 5,
        COLISTIN = 6,
        CEFALEXIN = 7,
        CEFADROXIL = 8,
        CEFOTAXIME = 9,
        CEFQUINOME = 10,
        CEFTIOFUR = 11,
        CEFTRIAXONE = 12,
        CHLOTETRACYLINE = 13,
        CLOXACILLIN = 14,
        CLINDAMYCIN = 15,
        CLARITHROMYCINE = 16,
        DANOFLOXACINE = 17,
        DOMYCYLINE = 18,
        DIHYDROSTREPTOMYCINE = 19,
        DIFLOXACINE = 20,
        DOXYCYLINE = 21,
        GENTAMYCIN = 22,
        FLUNIXIN = 23,
        KITASAMYCIN = 24,
        INCOMYCIN = 25,
        NEOMYCINE = 26,
        FLOFENICOL = 27,
        NYSTATIN = 28,
        KANAMYCIN = 29,
        JOSAMYCIN = 30,
        MARBOFLOXACINE = 31,
        METHIONINE = 32,
        NORFLOXACINE = 33,
        OXYTETRACYCLINE = 34,
        FLAVOMYCINE = 35,
        NETROMYCINE = 36,
        ERYTHROMYCINE = 37,
        ENROFLOXACINE = 38,
        FOSFOMICINE = 39,
        RIFAMYCINE = 40,
        SARAFLOXACINE = 41,
        SALINOMYCINE = 42,
        SPECTINOMYCINE = 43,
        SPRIRAMYCIN = 44,
        STREPTOMYCIN = 45,
        SULFACHLOPYRIDAZINE = 46,
        SULFADIMIDINE = 47,
        STRYCHONIN = 48,
        SULFADIAZINE = 49,
        SULLFADIMETHOXIN = 50,
        SULFADIMERAZINE = 51,
        SULFADOXINE = 52,
        SULFAMONOMETHOXIN = 53,
        SULFAQUINOXALINE = 54,
        SULAFAMETHOXYPYDIRAZINE = 55,
        SULFAMETHAZINE = 56,
        SULFAMERAZINE = 57,
        SULFACHLOROPYRAZINE = 58,
        SULFAGUANIDINE = 59,
        SULFACHLOZINE = 60,
        TERRAMYCINE = 61,
        TETRACYCLINE = 62,
        THIAMFENICOL = 63,
        TIAMULIN = 64,
        TILCOSIN = 65,
        TILMICOSIN = 66,
        L_CARNITINE = 67,
        TILOSIN = 68,
        TIMICOSIN = 69,
        TOBRAMYCIN = 70,
        TRIMETHOPRIME = 71,
        SULFAMETHOXAZOLE = 72,
        TULATHROMYCINE = 73,
        TYLOSIN = 74,
        TYLVALOSIN = 75,
        OXYMYKOIN = 76,
        RIBOFLAVIN = 77,
    }
}