namespace Ehr.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class DO : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.ActionAuditTrails",
                c => new
                    {
                        Id = c.Long(nullable: false, identity: true),
                        Username = c.String(),
                        DateTimeStamp = c.DateTime(nullable: false),
                        Action = c.String(),
                        Status = c.Int(nullable: false),
                        Actiontype = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.AntimicrobialRequireds",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Pet = c.String(),
                        BodyWeight = c.Double(nullable: false),
                        NumberOfPet = c.Int(nullable: false),
                        NumberOfPackage = c.Int(nullable: false),
                        VolumnPackage = c.Double(nullable: false),
                        APA = c.Double(nullable: false),
                        SA = c.Double(nullable: false),
                        AAA = c.Double(nullable: false),
                        ABW = c.Double(nullable: false),
                        AAA_ABW = c.Double(nullable: false),
                        DF = c.Double(nullable: false),
                        DI = c.Double(nullable: false),
                        TA = c.Double(nullable: false),
                        ADDKg = c.Double(nullable: false),
                        QuestionnaireId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.AuditTrails",
                c => new
                    {
                        Id = c.Long(nullable: false, identity: true),
                        KeyFieldID = c.Long(nullable: false),
                        AuditActionType = c.Int(nullable: false),
                        DateTimeStamp = c.DateTime(nullable: false),
                        DataModel = c.String(),
                        Changes = c.String(),
                        ValueBefore = c.String(),
                        ValueAfter = c.String(),
                        Username = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.LoginAuditTrails",
                c => new
                    {
                        Id = c.Long(nullable: false, identity: true),
                        Username = c.String(),
                        DateTimeStamp = c.DateTime(nullable: false),
                        IpAddress = c.String(),
                        Status = c.Int(nullable: false),
                        Note = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.MailConfigs",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ServerAddress = c.String(),
                        Port = c.Int(nullable: false),
                        Timeout = c.Int(nullable: false),
                        UseSSL = c.Boolean(nullable: false),
                        EmailSend = c.String(),
                        EmailCC = c.String(),
                        Username = c.String(),
                        Password = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Permissions",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PermissionName = c.String(),
                        PermissionCode = c.String(maxLength: 20),
                        PermisstionStatus = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .Index(t => t.PermissionCode, unique: true);
            
            CreateTable(
                "dbo.Roles",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        RoleName = c.String(),
                        RoleStatus = c.Int(nullable: false),
                        IsRoot = c.Int(nullable: false),
                        Role = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Users",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Username = c.String(maxLength: 50),
                        Password = c.String(nullable: false),
                        IsActive = c.Boolean(nullable: false),
                        FullName = c.String(),
                        Image = c.String(),
                        Email = c.String(),
                        PhoneNumber = c.String(),
                        Address = c.String(),
                        ResetPasswordCode = c.String(),
                        ConfirmPasswordCode = c.String(),
                    })
                .PrimaryKey(t => t.Id)
                .Index(t => t.Username, unique: true);
            
            CreateTable(
                "dbo.ProductRequireds",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Pet = c.String(),
                        NumberOfPet = c.Int(nullable: false),
                        NumberOfDate = c.Int(nullable: false),
                        KgOfPet = c.Double(nullable: false),
                        WP = c.Double(nullable: false),
                        DF = c.Double(nullable: false),
                        DI = c.Double(nullable: false),
                        NumberOfProductRequired = c.Double(nullable: false),
                        QuestionnaireId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Questionnaires",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        D_u_th_i_gian = c.DateTime(nullable: false),
                        A1__Product_origin = c.String(),
                        A2__Product_code = c.String(),
                        A3__Product_name = c.String(),
                        A4__Company = c.String(),
                        A5__Type_of_product = c.String(),
                        A6__Other_subtance_in_product = c.String(),
                        A7__Volume_of_product = c.String(),
                        A8__Unit_of_volume_of_product = c.String(),
                        A9__Other_volume_of_product = c.String(),
                        B1__Number_of_antimicrobials_in_product = c.Int(nullable: false),
                        B2_1__Antimicrobial_1 = c.String(),
                        B2_2__Strength_of_antimicrobial_1 = c.Double(nullable: false),
                        B2_3__Units_of_antimicrobial_1 = c.String(),
                        B2_4__Per_amount_of_product__antimicrobial_1_ = c.String(),
                        B2_5__Units_of_antimicrobial_1__link_to_question_B2_4_ = c.String(),
                        B2_6__Per_amount_of_product__volume_of_product___link_to_question_B2_4_ = c.String(),
                        B2_7__Units_of_product__link_to_question_B2_4_ = c.String(),
                        B3_1__Antimicrobial_2 = c.String(),
                        B3_2__Strength_of_antimicrobial_2 = c.Double(nullable: false),
                        B3_3__Units_of_antimicrobial_2 = c.String(),
                        B3_4__Per_amount_of_product__antimicrobial_2_ = c.String(),
                        B3_5__Units_of_antimicrobial_2__link_to_question_B3_4_ = c.String(),
                        B3_6__Per_amount_of_product__volume_of_product___link_to_question_B3_4_ = c.String(),
                        B3_7__Units_of_product__link_to_question_B3_4_ = c.String(),
                        B4_1__Antimicrobial_3 = c.String(),
                        B4_2__Strength_of_antimicrobial_3 = c.Double(nullable: false),
                        B4_3__Units_of_antimicrobial_3 = c.String(),
                        B4_4__Per_amount_of_product__antimicrobial_3_ = c.String(),
                        B4_5__Units_of_antimicrobial_3__link_to_question_B4_4_ = c.String(),
                        B4_6__Per_amount_of_product__volume_of_product___link_to_question_B4_4_ = c.String(),
                        B4_7__Units_of_product__link_to_question_B4_4_ = c.String(),
                        B5_1__Antimicrobial_4 = c.String(),
                        B5_2__Strength_of_antimicrobial_4 = c.Double(nullable: false),
                        B5_3__Units_of_antimicrobial_4 = c.String(),
                        B5_4__Per_amount_of_product__antimicrobial_4_ = c.String(),
                        B5_5__Units_of_antimicrobial_4__link_to_question_5_4_ = c.String(),
                        B5_6__Per_amount_of_product__volume_of_product___link_to_question_B5_4_ = c.String(),
                        B5_7__Units_of_product__link_to_question_B5_4_ = c.String(),
                        B6__Target_species_x = c.String(),
                        B7__Administration_route = c.String(),
                        C1_1__Product_preparation__dilution__Product_amount = c.String(),
                        C1_2__Product_preparation_Unit_of_product = c.String(),
                        C1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        C1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        C1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        C1_6__Duration_of_usage__min__max_ = c.String(),
                        C2_1__Product_min = c.String(),
                        C2_2__Product_max = c.String(),
                        C2_3__Unit_of_product = c.String(),
                        C2_4__Per_No__Kg_bodyweight_min = c.String(),
                        C2_5__Per_No__Kg_bodyweight_max = c.String(),
                        C2_6__Duration_of_usage = c.String(),
                        C3_1__Product_preparation__dilution__Product_amount = c.String(),
                        C3_2__Product_preparation_Unit_of_product = c.String(),
                        C3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        C3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        C3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        C3_6__Duration_of_usage = c.String(),
                        C4_1__Product_min = c.String(),
                        C4_2__Product_max = c.String(),
                        C4_3__Unit_of_product = c.String(),
                        C4_4__Per_No__Kg_bodyweight_min = c.String(),
                        C4_5__Per_No__Kg_bodyweight_max = c.String(),
                        C4_6__Duration_of_usage = c.String(),
                        D1_1__Product_preparation__dilution__Product_amount = c.String(),
                        D1_2__Product_preparation_Unit_of_product = c.String(),
                        D1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        D1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        D1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        D1_6__Duration_of_usage = c.String(),
                        D2_1__Product_min = c.String(),
                        D2_2__Product_max = c.String(),
                        D2_3__Unit_of_product = c.String(),
                        D2_4__Per_No__Kg_bodyweight_min = c.String(),
                        D2_5__Per_No__Kg_bodyweight_max = c.String(),
                        D2_6__Duration_of_usage = c.String(),
                        D3_1__Product_preparation__dilution__Product_amount = c.String(),
                        D3_2__Product_preparation_Unit_of_product = c.String(),
                        D3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        D3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        D3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        D3_6__Duration_of_usage = c.String(),
                        D4_1__Product_min = c.String(),
                        D4_2__Product_max = c.String(),
                        D4_3__Unit_of_product = c.String(),
                        D4_4__Per_No__Kg_bodyweight_min = c.String(),
                        D4_5__Per_No__Kg_bodyweight_max = c.String(),
                        D4_6__Duration_of_usage = c.String(),
                        E1_1__Product_preparation__dilution__Product_amount = c.String(),
                        E1_2__Product_preparation_Unit_of_product = c.String(),
                        E1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        E1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        E1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        E1_6__Duration_of_usage = c.String(),
                        E2_1__Product_min = c.String(),
                        E2_2__Product_max = c.String(),
                        E2_3__Unit_of_product = c.String(),
                        E2_4__Per_No__Kg_bodyweight_min = c.String(),
                        E2_5__Per_No__Kg_bodyweight_max = c.String(),
                        E2_6__Duration_of_usage = c.String(),
                        E3_1__Product_preparation__dilution__Product_amount = c.String(),
                        E3_2__Product_preparation_Unit_of_product = c.String(),
                        E3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        E3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        E3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        E3_6__Duration_of_usage = c.String(),
                        E4_1__Product_min = c.String(),
                        E4_2__Product_max = c.String(),
                        E4_3__Unit_of_product = c.String(),
                        E4_4_Per_No__Kg_bodyweight_min = c.String(),
                        E4_5__Per_No__Kg_bodyweight_max = c.String(),
                        E4_6__Duration_of_usage = c.String(),
                        F_1__Source_of_information = c.String(),
                        F_2__Picture_of_product = c.String(),
                        F3__Correction = c.String(),
                        F_4__Person_in_charge = c.String(),
                        F_5__Working_time = c.String(),
                        F_6__Note = c.String(),
                        Piglet_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Piglet_1_2__Product_preparation_Unit_of_product = c.String(),
                        Piglet_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Piglet_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Piglet_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Piglet_1_6__Duration_of_usage = c.String(),
                        Piglet_2_1__Product_min = c.String(),
                        Piglet_2_2__Product_max = c.String(),
                        Piglet_2_3__Unit_of_product = c.String(),
                        Piglet_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Piglet_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Piglet_2_6__Duration_of_usage = c.String(),
                        Piglet_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Piglet_3_2__Product_preparation_Unit_of_product = c.String(),
                        Piglet_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Piglet_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Piglet_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Piglet_3_6__Duration_of_usage = c.String(),
                        Piglet_4_1__Product_min = c.String(),
                        Piglet_4_2__Product_max = c.String(),
                        Piglet_4_3__Unit_of_product = c.String(),
                        Piglet_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Piglet_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Piglet_4_6__Duration_of_usage = c.String(),
                        Buffalo_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Buffalo_1_2__Product_preparation_Unit_of_product = c.String(),
                        Buffalo_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Buffalo_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Buffalo_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Buffalo_1_6__Duration_of_usage = c.String(),
                        Buffalo_2_1__Product_min = c.String(),
                        Buffalo_2_2__Product_max = c.String(),
                        Buffalo_2_3__Unit_of_product = c.String(),
                        Buffalo_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Buffalo_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Buffalo_2_6__Duration_of_usage = c.String(),
                        Buffalo_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Buffalo_3_2__Product_preparation_Unit_of_product = c.String(),
                        Buffalo_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Buffalo_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Buffalo_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Buffalo_3_6__Duration_of_usage = c.String(),
                        Buffalo_4_1__Product_min = c.String(),
                        Buffalo_4_2__Product_max = c.String(),
                        Buffalo_4_3__Unit_of_product = c.String(),
                        Buffalo_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Buffalo_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Buffalo_4_6__Duration_of_usage = c.String(),
                        Cattle_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Cattle_1_2__Product_preparation_Unit_of_product = c.String(),
                        Cattle_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Cattle_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Cattle_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Cattle_1_6__Duration_of_usages = c.String(),
                        Cattle_2_1__Product_min = c.String(),
                        Cattle_2_2__Product_max = c.String(),
                        Cattle_2_3__Unit_of_product = c.String(),
                        Cattle_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Cattle_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Cattle_2_6__Duration_of_usage = c.String(),
                        Cattle_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Cattle_3_2__Product_preparation_Unit_of_product = c.String(),
                        Cattle_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Cattle_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Cattle_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Cattle_3_6__Duration_of_usage = c.String(),
                        Cattle_4_1__Product_min = c.String(),
                        Cattle_4_2__Product_max = c.String(),
                        Cattle_4_3__Unit_of_product = c.String(),
                        Cattle_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Cattle_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Cattle_4_6__Duration_of_usage = c.String(),
                        Goat_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Goat_1_2__Product_preparation_Unit_of_product = c.String(),
                        Goat_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Goat_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Goat_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Goat_1_6__Duration_of_usage = c.String(),
                        Goat_2_1__Product_min = c.String(),
                        Goat_2_2__Product_max = c.String(),
                        Goat_2_3__Unit_of_product = c.String(),
                        Goat_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Goat_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Goat_2_6__Duration_of_usage = c.String(),
                        Goat_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Goat_3_2__Product_preparation_Unit_of_product = c.String(),
                        Goat_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Goat_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Goat_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Goat_3_6__Duration_of_usage = c.String(),
                        Goat_4_1__Product_min = c.String(),
                        Goat_4_2__Product_max = c.String(),
                        Goat_4_3__Unit_of_product = c.String(),
                        Goat_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Goat_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Goat_4_6__Duration_of_usage = c.String(),
                        Sheep_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Sheep_1_2__Product_preparation_Unit_of_product = c.String(),
                        Sheep_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Sheep_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Sheep_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Sheep_1_6__Duration_of_usage = c.String(),
                        Sheep_2_1__Product_min = c.String(),
                        Sheep_2_2__Product_max = c.String(),
                        Sheep_2_3__Unit_of_product = c.String(),
                        Sheep_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Sheep_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Sheep_2_6__Duration_of_usage = c.String(),
                        Sheep_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Sheep_3_2__Product_preparation_Unit_of_product = c.String(),
                        Sheep_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Sheep_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Sheep_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Sheep_3_6__Duration_of_usage = c.String(),
                        Sheep_4_1__Product_min = c.String(),
                        Sheep_4_2__Product_max = c.String(),
                        Sheep_4_3__Unit_of_product = c.String(),
                        Sheep_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Sheep_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Sheep_4_6__Duration_of_usage = c.String(),
                        Horse_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Horse_1_2__Product_preparation_Unit_of_product = c.String(),
                        Horse_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Horse_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Horse_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Horse_1_6__Duration_of_usage = c.String(),
                        Horse_2_1__Product_min = c.String(),
                        Horse_2_2__Product_max = c.String(),
                        Horse_2_3__Unit_of_product = c.String(),
                        Horse_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Horse_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Horse_2_6__Duration_of_usage = c.String(),
                        Horse_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Horse_3_2__Product_preparation_Unit_of_product = c.String(),
                        Horse_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Horse_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Horse_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Horse_3_6__Duration_of_usage = c.String(),
                        Horse_4_1__Product_min = c.String(),
                        Horse_4_2__Product_max = c.String(),
                        Horse_4_3__Unit_of_product = c.String(),
                        Horse_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Horse_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Horse_4_6__Duration_of_usage = c.String(),
                        Chicken_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Chicken_1_2__Product_preparation_Unit_of_product = c.String(),
                        Chicken_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Chicken_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Chicken_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Chicken_1_6__Duration_of_usage = c.String(),
                        Chicken_2_1__Product_min = c.String(),
                        Chicken_2_2__Product_max = c.String(),
                        Chicken_2_3__Unit_of_product = c.String(),
                        Chicken_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Chicken_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Chicken_2_6__Duration_of_usage = c.String(),
                        Chicken_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Chicken_3_2__Product_preparation_Unit_of_product = c.String(),
                        Chicken_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Chicken_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Chicken_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Chicken_3_6__Duration_of_usage = c.String(),
                        Chicken_4_1__Product_min = c.String(),
                        Chicken_4_2__Product_max = c.String(),
                        Chicken_4_3__Unit_of_product = c.String(),
                        Chicken_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Chicken_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Chicken_4_6__Duration_of_usage = c.String(),
                        Duck_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Duck_1_2__Product_preparation_Unit_of_product = c.String(),
                        Duck_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Duck_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Duck_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Duck_1_6__Duration_of_usage = c.String(),
                        Duck_2_1__Product_min = c.String(),
                        Duck_2_2__Product_max = c.String(),
                        Duck_2_3__Unit_of_product = c.String(),
                        Duck_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Duck_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Duck_2_6__Duration_of_usage = c.String(),
                        Duck_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Duck_3_2__Product_preparation_Unit_of_product = c.String(),
                        Duck_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Duck_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Duck_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Duck_3_6__Duration_of_usage = c.String(),
                        Duck_4_1__Product_min = c.String(),
                        Duck_4_2__Product_max = c.String(),
                        Duck_4_3__Unit_of_product = c.String(),
                        Duck_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Duck_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Duck_4_6__Duration_of_usage = c.String(),
                        Muscovy_Duck_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Muscovy_Duck_1_2__Product_preparation_Unit_of_product = c.String(),
                        Muscovy_Duck_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Muscovy_Duck_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Muscovy_Duck_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Muscovy_Duck_1_6__Duration_of_usage = c.String(),
                        Muscovy_Duck_2_1__Product_min = c.String(),
                        Muscovy_Duck_2_2__Product_max = c.String(),
                        Muscovy_Duck_2_3__Unit_of_product = c.String(),
                        Muscovy_Duck_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Muscovy_Duck_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Muscovy_Duck_2_6__Duration_of_usage = c.String(),
                        Muscovy_Duck_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Muscovy_Duck_3_2__Product_preparation_Unit_of_product = c.String(),
                        Muscovy_Duck_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Muscovy_Duck_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Muscovy_Duck_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Muscovy_Duck_3_6__Duration_of_usage = c.String(),
                        Muscovy_Duck_4_1__Product_min = c.String(),
                        Muscovy_Duck_4_2__Product_max = c.String(),
                        Muscovy_Duck_4_3__Unit_of_product = c.String(),
                        Muscovy_Duck_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Muscovy_Duck_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Muscovy_Duck_4_6__Duration_of_usage = c.String(),
                        Quail_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Quail_1_2__Product_preparation_Unit_of_product = c.String(),
                        Quail_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Quail_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Quail_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Quail_1_6__Duration_of_usage = c.String(),
                        Quail_2_1__Product_min = c.String(),
                        Quail_2_2__Product_max = c.String(),
                        Quail_2_3__Unit_of_product = c.String(),
                        Quail_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Quail_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Quail_2_6__Duration_of_usage = c.String(),
                        Quail_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Quail_3_2__Product_preparation_Unit_of_product = c.String(),
                        Quail_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Quail_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Quail_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Quail_3_6__Duration_of_usage = c.String(),
                        Quail_4_1__Product_min = c.String(),
                        Quail_4_2__Product_max = c.String(),
                        Quail_4_3__Unit_of_product = c.String(),
                        Quail_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Quail_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Quail_4_6__Duration_of_usage = c.String(),
                        Goose_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Goose_1_2__Product_preparation_Unit_of_product = c.String(),
                        Goose_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Goose_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Goose_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Goose_1_6__Duration_of_usage = c.String(),
                        Goose_2_1__Product_min = c.String(),
                        Goose_2_2__Product_max = c.String(),
                        Goose_2_3__Unit_of_product = c.String(),
                        Goose_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Goose_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Goose_2_6__Duration_of_usage = c.String(),
                        Goose_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Goose_3_2__Product_preparation_Unit_of_product = c.String(),
                        Goose_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Goose_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Goose_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Goose_3_6__Duration_of_usage = c.String(),
                        Goose_4_1__Product_min = c.String(),
                        Goose_4_2__Product_max = c.String(),
                        Goose_4_3__Unit_of_product = c.String(),
                        Goose_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Goose_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Goose_4_6__Duration_of_usage = c.String(),
                        Dog_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Dog_1_2__Product_preparation_Unit_of_product = c.String(),
                        Dog_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Dog_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Dog_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Dog_1_6__Duration_of_usage = c.String(),
                        Dog_2_1__Product_min = c.String(),
                        Dog_2_2__Product_max = c.String(),
                        Dog_2_3__Unit_of_product = c.String(),
                        Dog_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Dog_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Dog_2_6__Duration_of_usage = c.String(),
                        Dog_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Dog_3_2__Product_preparation_Unit_of_product = c.String(),
                        Dog_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Dog_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Dog_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Dog_3_6__Duration_of_usage = c.String(),
                        Dog_4_1__Product_min = c.String(),
                        Dog_4_2__Product_max = c.String(),
                        Dog_4_3__Unit_of_product = c.String(),
                        Dog_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Dog_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Dog_4_6__Duration_of_usage = c.String(),
                        Cat_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Cat_1_2__Product_preparation_Unit_of_product = c.String(),
                        Cat_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Cat_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Cat_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Cat_1_6__Duration_of_usage = c.String(),
                        Cat_2_1__Product_min = c.String(),
                        Cat_2_2__Product_max = c.String(),
                        Cat_2_3__Unit_of_product = c.String(),
                        Cat_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Cat_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Cat_2_6__Duration_of_usage = c.String(),
                        Cat_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Cat_3_2__Product_preparation_Unit_of_product = c.String(),
                        Cat_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Cat_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Cat_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Cat_3_6__Duration_of_usage = c.String(),
                        Cat_4_1__Product_min = c.String(),
                        Cat_4_2__Product_max = c.String(),
                        Cat_4_3__Unit_of_product = c.String(),
                        Cat_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Cat_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Cat_4_6__Duration_of_usage = c.String(),
                        Calf_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Calf_1_2__Product_preparation_Unit_of_product = c.String(),
                        Calf_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Calf_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Calf_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Calf_1_6__Duration_of_usage = c.String(),
                        Calf_2_1__Product_min = c.String(),
                        Calf_2_2__Product_max = c.String(),
                        Calf_2_3__Unit_of_product = c.String(),
                        Calf_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Calf_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Calf_2_6__Duration_of_usage = c.String(),
                        Calf_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Calf_3_2__Product_preparation_Unit_of_product = c.String(),
                        Calf_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Calf_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Calf_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Calf_3_6__Duration_of_usage = c.String(),
                        Calf_4_1__Product_min = c.String(),
                        Calf_4_2__Product_max = c.String(),
                        Calf_4_3__Unit_of_product = c.String(),
                        Calf_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Calf_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Calf_4_6__Duration_of_usage = c.String(),
                        Chick_1_1__Product_preparation__dilution__Product_amount = c.String(),
                        Chick_1_2__Product_preparation_Unit_of_product = c.String(),
                        Chick_1_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Chick_1_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Chick_1_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Chick_1_6__Duration_of_usage = c.String(),
                        Chick_2_1__Product_min = c.String(),
                        Chick_2_2__Product_max = c.String(),
                        Chick_2_3__Unit_of_product = c.String(),
                        Chick_2_4__Per_No__Kg_bodyweight_min = c.String(),
                        Chick_2_5__Per_No__Kg_bodyweight_max = c.String(),
                        Chick_2_6__Duration_of_usage = c.String(),
                        Chick_3_1__Product_preparation__dilution__Product_amount = c.String(),
                        Chick_3_2__Product_preparation_Unit_of_product = c.String(),
                        Chick_3_3__Product_preparation_To_be_added_to__min_ = c.String(),
                        Chick_3_4__Product_preparation_To_be_added_to__max_ = c.String(),
                        Chick_3_5__Product_preparation_Unit_of_water_feed = c.String(),
                        Chick_3_6__Duration_of_usage = c.String(),
                        Chick_4_1__Product_min = c.String(),
                        Chick_4_2__Product_max = c.String(),
                        Chick_4_3__Unit_of_product = c.String(),
                        Chick_4_4_Per_No__Kg_bodyweight_min = c.String(),
                        Chick_4_5__Per_No__Kg_bodyweight_max = c.String(),
                        Chick_4_6__Duration_of_usage = c.String(),
                        keyupload = c.String(),
                        State = c.Int(nullable: false),
                        CreateBy_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.CreateBy_Id)
                .Index(t => t.CreateBy_Id);
            
            CreateTable(
                "dbo.References",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Pet = c.String(),
                        PetNameDetail = c.String(),
                        Week = c.Int(nullable: false),
                        Volume_Min = c.Int(nullable: false),
                        Volume_Max = c.Int(nullable: false),
                        Volume_AVG = c.Int(nullable: false),
                        Volume_Food_Min = c.Int(nullable: false),
                        Volume_Food_Max = c.Int(nullable: false),
                        Volume_Food_AVG = c.Int(nullable: false),
                        Volume_Water_Min = c.Int(nullable: false),
                        Volume_Water_Max = c.Int(nullable: false),
                        Volume_Water_AVG = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.RolePermissions",
                c => new
                    {
                        Role_Id = c.Int(nullable: false),
                        Permission_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.Role_Id, t.Permission_Id })
                .ForeignKey("dbo.Roles", t => t.Role_Id, cascadeDelete: true)
                .ForeignKey("dbo.Permissions", t => t.Permission_Id, cascadeDelete: true)
                .Index(t => t.Role_Id)
                .Index(t => t.Permission_Id);
            
            CreateTable(
                "dbo.UserRoles",
                c => new
                    {
                        User_Id = c.Int(nullable: false),
                        Role_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.User_Id, t.Role_Id })
                .ForeignKey("dbo.Users", t => t.User_Id, cascadeDelete: true)
                .ForeignKey("dbo.Roles", t => t.Role_Id, cascadeDelete: true)
                .Index(t => t.User_Id)
                .Index(t => t.Role_Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Questionnaires", "CreateBy_Id", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "Role_Id", "dbo.Roles");
            DropForeignKey("dbo.UserRoles", "User_Id", "dbo.Users");
            DropForeignKey("dbo.RolePermissions", "Permission_Id", "dbo.Permissions");
            DropForeignKey("dbo.RolePermissions", "Role_Id", "dbo.Roles");
            DropIndex("dbo.UserRoles", new[] { "Role_Id" });
            DropIndex("dbo.UserRoles", new[] { "User_Id" });
            DropIndex("dbo.RolePermissions", new[] { "Permission_Id" });
            DropIndex("dbo.RolePermissions", new[] { "Role_Id" });
            DropIndex("dbo.Questionnaires", new[] { "CreateBy_Id" });
            DropIndex("dbo.Users", new[] { "Username" });
            DropIndex("dbo.Permissions", new[] { "PermissionCode" });
            DropTable("dbo.UserRoles");
            DropTable("dbo.RolePermissions");
            DropTable("dbo.References");
            DropTable("dbo.Questionnaires");
            DropTable("dbo.ProductRequireds");
            DropTable("dbo.Users");
            DropTable("dbo.Roles");
            DropTable("dbo.Permissions");
            DropTable("dbo.MailConfigs");
            DropTable("dbo.LoginAuditTrails");
            DropTable("dbo.AuditTrails");
            DropTable("dbo.AntimicrobialRequireds");
            DropTable("dbo.ActionAuditTrails");
        }
    }
}
